.TH "ZWT" 1 "May 16 2024" "zwt 1.1.3" "User Commands"
.SH NAME
zwt \- zsh-window-title CLI

.SH SYNOPSIS

\fBzwt restore-defaults\fR

.SH DESCRIPTION

\fBzwt\fR is the CLI for managing the zsh plugin \fBzsh-window-title\fR.

.SH Commands

.IP \(bu
\fBrestore-defaults\fR

Restore options to their defaults.

.IP \(bu
\fBhelp\fR or \fB\-\-help\fR or \fB\-h\fR

Show the manpage.

.IP \(bu
\fBversion\fR or \fB\-\-version\fR or \fB\-v\fR

Print the command name and current version.

.SH Configuration
The following variables may be set:

.IP \(bu
\fIZSH_WINDOW_TITLE_COMMAND_PREFIXES\fR
If the command starts with one of these terms, show it and the following word.
With the default, running `sudo sleep 10` will add `sudo sleep`
to the window title. (array; default `( sudo )`)

.IP \(bu
\fIZSH_WINDOW_TITLE_DEBUG\fR
If non-zero, print hook debugging messages (integer; default `0`)

.IP \(bu
\fIZSH_WINDOW_TITLE_DIRECTORY_DEPTH\fR
How many directory levels to display (integer; default `2`)

.IP \(bu
\fIZWT_DEBUG\fR
If non-zero, print CLI debugging messages (integer; default `0`)

.\" .SH EXAMPLES

.SH LICENSE

Licensed under CC BY-NC-SA 4.0 with a human rights condition from Hippocratic
License 2.1. See the LICENSE file for details. Persons interested in using or
adapting this work for commercial purposes should contact the author.

.SH HOMEPAGE

Explanations and examples can be found at https://github.com/olets/zsh-window-title

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
