.TH "ZWT" 1 "September 26 2021" "zwt 1.0.2" "User Commands"
.SH NAME
zwt \- zsh-window-title CLI

.SH SYNOPSIS

\fBzwt restore-defaults\fR

.SH DESCRIPTION

\fBzwt\fR is the CLI for managing the zsh plugin \fBzsh-window-title\fR.

.SH Commands

.IP \(bu
\fBrestore-defaults\fR

Restore options to their defaults.

.IP \(bu
\fBhelp\fR or \fB\-\-help\fR or \fB\-h\fR

Show the manpage.

.IP \(bu
\fBversion\fR or \fB\-\-version\fR or \fB\-v\fR

Print the command name and current version.

.\" .SH EXAMPLES

.SH LICENSE

Licensed under CC BY-NC-SA 4.0 with a human rights condition from Hippocratic
License 2.1. See the LICENSE file for details. Persons interested in using or
adapting this work for commercial purposes should contact the author.

.SH HOMEPAGE

Explanations and examples can be found at https://github.com/olets/zsh-window-title

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
